### ISSUE TITLE
Bug: /channel/:channelId/home 에서 화면 렌더링 불가 버그

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#108]
**버그를 설명해주세요**
1. /channel/:channelId/home 에서 맨처음 접속은 렌더링이 잘 되지만, 재능공유요청 탭이나 재능공유채팅 탭 등 다른 탭에 갔다가 오면 렌더링이 되지 않고 하얀 화면이 뜹니다.
2. 채널홈에서 오픈된 채팅방 목록과 채널 재능공유 요청 목록이 있지만 없다고 뜹니다.

**재현방법**
버그를 재현하려면...
1. 프로덕션 사이트 / 로컬에서 열은 클라이언트 접속(디버깅을 위해 로컬 권장)
2. 로그인, 본인이 속한 채널(해당 버그에선 id: 1 채널에서 발생)로 이동
3. 채널 홈 접속
4. 3에서 잘 렌더링될 경우 재능공유요청 탭 등 다른 탭을 갔다가 다시 채널 홈으로 이동

**맞는 동작**
채널 홈이 잘 렌더링 되어야 합니다.

**스크린샷**
1. 채널 재능공유 요청이 없다고 하는 문제 원인?
![캡처3](https://user-images.githubusercontent.com/38745815/136874563-c739380b-46cc-4e34-a2b7-66ef787b4716.png)
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/2ded8ce4442c1d1c8b27df708b4d10ef27f0fac5/src/containers/channel/ChannelHomeContainer.jsx#L14-L18
2. 채널 오픈된 채팅방이 없다고 하는 문제 원인?
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/2ded8ce4442c1d1c8b27df708b4d10ef27f0fac5/src/components/channel/ChannelHome.jsx#L77-L98
![캡처3](https://user-images.githubusercontent.com/38745815/136875448-11b9ee43-1b5b-4f5d-81c8-99dada9b7d75.png)
api 요청도 성공하고, 리덕스 스토어에도 잘 들어갔음.
3. 채널홈 렌더링 되지 않는 문제 원인?
![캡처3](https://user-images.githubusercontent.com/38745815/136875719-f8ec63db-5bb3-4e93-993f-472ca0a4a70e.png)
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/2ded8ce4442c1d1c8b27df708b4d10ef27f0fac5/src/components/channel/PostCard.jsx#L25-L27
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/2ded8ce4442c1d1c8b27df708b4d10ef27f0fac5/src/lib/util/postType.js#L1-L14
postType에 Archived가 추가되어야 할것 같음. 서버에서 주는 post데이터 중에 status value가 Archived 상태인 것이 이제 포함됩니다.

**추가적인 상황**
api 서버 측에 요청할 것이 있으면 슬랙으로 알려주세요.

**Comment by sjsjsj1246** [comment]
생각해보니 재능 공유요청 페이지만 만들고 채널 홈은 안건들였는데 좀있다 보겠습니다

**Comment by sjsjsj1246** [comment]
@KeisLuv5991  재능 공유 요청 리스트에선 쿼리를 주는데 홈에선 쿼리를 안줘서 생기는 오류인것 같습니다.
