### ISSUE TITLE
Bug: 랜딩페이지에 버튼을 누르면 화살표가 활성화 상태가 되지 않습니다! 그리고 이미지 화질이 많이 깨져요.

### ISSUE THREAD

**Issue by ssusukang** [Jandy-SeoulTech/Jandy_Web_Front#171]
랜딩페이지 시작하기 버튼 누르면 마우스 커서가 활성화 상태가 아니어서 활성화 상태가 되면 좋겠고,
이미지가 많이 깨져보여서 피그마에서 export할때 4X로 설정 한번 바꿔서 해주세요!

**Comment by sjsjsj1246** [comment]
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/issues/150
버튼 커서 문제는 위 이슈에서 다루는 문제입니다. 
이미지 화질도 위 이슈에서 다루고 현재 이슈는 닫겠습니다.
