### ISSUE TITLE
Bug: 채널 재능공유요청 목록 페이지 page 쿼리 유지

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#179]
**버그를 설명해주세요**
채널 재능 공유 요청 목록 페이지에서 전체 => 채팅 오픈 등으로 다른 탭으로 이동할때 page 쿼리가 유지됩니다. 즉 전체 탭에서 2페이지를 보고 있었다면 채팅오픈탭으로 이동했을 시 2페이지의 쿼리가 유지되어, 아무것도 렌더링 되지않습니다.

**맞는 동작**
1. 탭을 이동할때는 1페이지로 이동하거나, 
2. 각 탭에서의 마지막 페이지 쿼리를 기억하고 탭을 이동할때 마지막에 보고있던 페이지를 렌더링해야 합니다. 

**스크린샷**
![캡처](https://user-images.githubusercontent.com/38745815/138546376-b39da46a-b295-4018-9f38-0a0afd757cab.PNG)

**추가적인 상황**
문제를 해결하는데 도움되는 당시의 상황을 적어주세요.

**Comment by sjsjsj1246** [comment]
1번 방식으로 해결
