### ISSUE TITLE
Bug: 아카이브와 포스트를 이미지를 올리지 않고 글만 작성하면 등록 실패함

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#184]
**버그를 설명해주세요**
모아보기와 요청글을 이미지를 올리지않고 글만 작성하면 등록에 실패합니다. 
image 관련 validation에러가 나오는걸로 봐선 image 관련 문제입니다.

**맞는 동작**
이미지를 올리지않고 글만 작성해도 정상 등록되어야함.

**추가적인 상황**
문제를 해결하는데 도움되는 당시의 상황을 적어주세요.

**Comment by sjsjsj1246** [comment]
이미지 모듈의 images배열에 null값이 들어있어 에러가 난다고 하셨는데 정확한 상황은 잘 모르겠으나 #188 을 완료하고 나면 해결될 문제일 것 같습니다.
