### ISSUE TITLE
Bug: 닉네임 중복 확인

### ISSUE THREAD

**Issue by md2eoseo** [Jandy-SeoulTech/Jandy_Web_Front#209]
**버그를 설명해주세요**
닉네임 중복 확인이 바로 안됨

**Comment by md2eoseo** [comment]
@sjsjsj1246 @KeisLuv5991 버그 확인해보니 닉네임 입력을 빠르게 하면 요청을 여러번 보내게 되는데 가장 마지막으로 받은 응답의 닉네임 중복 확인 결과를 받아 이미 존재하는 닉네임임에도 불구하고 닉네임 결정 버튼이 활성화됩니다. 혹시 redux-pender로 비동기 처리 취소하는 방법 아시는 분 계시나요?
https://github.com/velopert/redux-pender#cancellation
이 내용을 찾아서 적용하려 하는데 잘 안되네요..

**Comment by sjsjsj1246** [comment]
어느 페이지에서 문제가 생기나요?
닉네임 중복체크는 되나요?
닉네임 중복체크에서 중복인 상황에서 닉네임 결정 버튼이 활성화되나요?

**Comment by md2eoseo** [comment]
네 중복 체크는 되는데 중복인 상황에서 닉네임 결정 버튼이 활성화됩니다. 소셜 가입 유저 닉네임 등록 페이지인 `SetNicknamePage`에서 버그 발생합니다.

**Comment by md2eoseo** [comment]
지금 db에 '샤브샤브'라는 닉네임 있는데 빠르게 입력하면 확인하실 수 있어요

**Comment by sjsjsj1246** [comment]
@md2eoseo 아.. 확인했습니다. 이전에 보낸 api 호출의 응답이 마지막에 보낸 호출보다 먼저 도착해서 이렇게 됐군요 제생각에는 닉네임이 중복일경우 서버에서 403 에러를 내는것부터가 문제가 좀 있다고 봅니다.
성공시에 data로 true를 보내주고 실패시에 data에 false를 보내는 식으로 하면 해결될것같은데요

**Comment by sjsjsj1246** [comment]
일정한 포멧을 보내주면 응답속도가 맞춰지지 않을까 생각합니다.

다른방법으로는 redux-saga써서 마지막 액션만 보내기, 닉네임을 입력할때마다 체크하지 않고 닉네임 체크 버튼을 만들기
정도가 있겠습니다.
