### ISSUE TITLE
데이터 연동

### ISSUE THREAD

**Issue by md2eoseo** [Jandy-SeoulTech/Jandy_Web_Front#38]
# Main Development
## 데이터 연동
각 페이지에서 서버측 API 고정 응답 또는 클라이언트에서 임시로 구현한 데이터를 실제 데이터로 교체하는 작업을 합니다.
## 구현되지 않은 기능 정리
이 외에 구현되지 않은 기능들을 이슈에 임시로 정리합니다.

# 작업사항
### 유저 프로필
- 모아 보기
- 오픈 채널
- 참여 채널
### 채널 프로필
- 모아 보기
### 채널 홈
- 게시판
- 오픈된 채팅방
- 모아 보기
### 채널 재능 공유 요청
- 게시물
### 채널 포스트
- 일치하는 포스트 표시하도록 구현 필요
### 채널 재능 공유 채팅
- 페이지 구현 필요
### 채널 모아 보기
- 페이지 구현 필요

**Comment by KeisLuv5991** [comment]
모아보기는 포스트/아카이빙 기능의 서비스 내에서 명칭인데, 마일스톤 2에 할당할 예정이니 이번 스프린트에서는 연동할 수 없습니다. 차후에 마일스톤 2에서 개발 후 연동하는 걸로 알겠습니다.

**Comment by md2eoseo** [comment]
모아보기 부분은 다음 스프린트에 등록할 수 있도록 뺐구요,
데이터 연동 태스크를 도메인 별로 분리하여 다시 이슈 등록했습니다!
3번 같은 경우에 개별 게시물 페이지는 또 다른 페이지라서 해당 기능 개발 시작 전에 따로 이슈 등록하겠습니다~

**Comment by KeisLuv5991** [comment]
넵!!
