### ISSUE TITLE
Auth Module 버그(닉네임 등록)

### ISSUE THREAD

**Issue by sjsjsj1246** [Jandy-SeoulTech/Jandy_Web_Front#68]
redux-pender로 마이그레이션하면서 다소 버그가 발생하는 듯 합니다.
닉네임 등록을 할 때 중복 체크를 하는데 중복체크가 안되는 버그가 발생했습니다.

기존 상태 업데이트 로직을 잘못 적용한 것 같아 수정하겠습니다.

---

알고보니 현재 Peding 상태인 PR을 병합하면 해결될 듯 합니다.

**Comment by Istiopaxx** [comment]
#66
