### ISSUE TITLE
닉네임 등록 후 결정 버튼을 눌러도 반응 없음 

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#69]
![캡처](https://user-images.githubusercontent.com/38745815/135761284-386877f1-869d-4c6c-a68f-526d5202dea7.PNG)

develop 브랜치 기준입니다.

닉네임 체크 로직은 잘 작동하는데 결정 버튼을 누르면 api 요청은 정상적으로 가고, 닉네임도 등록 됨. 근데 다음 페이지로 넘어가지 않음. 
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/containers/profile/SetNicknameContainer.jsx#L29-L31
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/modules/auth.js#L20
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/modules/auth.js#L67-L73

https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/containers/profile/SetNicknameContainer.jsx#L39-L45
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/modules/user.js#L17
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/0a181211dd1f570a7ac8ac44ec7ef4649247e254/src/modules/user.js#L29-L32

히스토리 이동이 안먹히는것같습니다.

**Comment by sjsjsj1246** [comment]
손보겠습니다
