### ISSUE TITLE
재능 공유 요청 작성시 라우터 겹침

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#73]
https://github.com/Jandy-SeoulTech/Jandy_Web_Front/blob/512e4a669d9645e6ea7fd75febcfabcc6dc865b7/src/routers/ChannelRouter.jsx#L23-L30

라우터가 edit이란 문자열을 포스트id로 인식해서 exact를 붙혀도 두개 다 렌더링함.
수정 혹은 신규 작성 모두 writing으로 통일하는 방식으로 #71 에서 해결하겠음.

**Comment by sjsjsj1246** [comment]
```js
      <Route
        path="/channel/:channelId/post/:postId"
        exact
        render={(props) => <CheckJoinChannel {...props} Component={ChannelPostPage} />}
      />
      <Route
        path="/channel/:channelId/post/:postId/edit"
        render={(props) => <CheckJoinChannel {...props} Component={ChannelPostEditPage} />}
      />
```

이렇게 처리해야 할 것 같네요 포스트 수정시에도 postId가 필요할겁니다.
수정 로직이 아직 제대로 있지는 않은것같지만요

**Comment by Istiopaxx** [comment]
채널 포스트 수정, 채널 포스트 작성 둘다 ChannelPostWriting 페이지를 활용하도록 하고 라우팅은 제안해준걸로 할게요옹~~

**Comment by sjsjsj1246** [comment]
생각해보니 이거 하나만 있으면 될 것 같습니다.
      <Route
        path="/channel/:channelId/writing"
        render={(props) => <CheckJoinChannel {...props} Component={ChannelPostWritingPage} />}
      />
포스트를 수정할 때는 수정버튼을 눌렀을 때 리덕스에 기존 포스트 데이터를 올려서 수정처리해주면됩니다.

**Comment by Istiopaxx** [comment]
#80 에서 완전히 해결되지 않았습니다. 차후 PR에서 해결 예정.
