### ISSUE TITLE
채널 재능 공유 요청에서 채팅방 만들기 할 시 라우터 꼬임

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#75]
채널 재능 공유 요청에서 채팅방 만들기를 클릭해 모달에서 바로 열기를 누르면,
1. 새창으로 열리지 않습니다.
2. 라우터가 꼬여서 제대로 렌더링 되지 않습니다.
`http://localhost:3000/channel/2/post/channel/2/chat`

**Comment by sjsjsj1246** [comment]
그부분은 제가 제대로 안해본것 같네요 바로 해보겠습니다.
