### ISSUE TITLE
Post 모듈 분리 제안

### ISSUE THREAD

**Issue by sjsjsj1246** [Jandy-SeoulTech/Jandy_Web_Front#79]
현재 채널 공유 요청이 Post이고 Channel 모듈 안에 Post가 있습니다.
그런데 채널이 너무 비대해지고 post또한 관련 로직이 많을 것 같기 때문에 모듈을 분리하는것이 맞는것 같습니다.(chat처럼)

channel -> channel, post

**Comment by md2eoseo** [comment]
네 말씀대로 모듈이 많이 커져서 분리하는게 좋을 것 같습니다.
그리고 각 포스트는 postId로 특정지어지니 `/channel/:channelId/post/:postId` 라우터를 `/post/:postId`처럼 축소해서 `getChannelData` 요청을 지우고 channel 모듈에 요청하는 횟수를 줄이는건 어떨까요?

**Comment by sjsjsj1246** [comment]
@md2eoseo 네 그렇게 해보겠습니다.
