### ISSUE TITLE
이미지 API url 리펙토링 관련 코드 수정

### ISSUE THREAD

**Issue by sjsjsj1246** [Jandy-SeoulTech/Jandy_Web_Front#91]
백엔드에서 이미지url 구조 관련 리펙토링을 하여 이에 관해 코드를 수정하겠습니다.
- Achive
- Channel
- ChannelRoom
- ChatMessage
- Comment
- Post
- Proofile
- Review
- Room
- User

**Comment by Istiopaxx** [comment]
해당부분 1순위로 진행하겠습니다. 서버 업데이트되었더니 배포에서 모두 오류가 나서 사이트를 볼수가 없네요~~

**Comment by sjsjsj1246** [comment]
@KeisLuv5991 지금 하고있습니다~
