### ISSUE TITLE
채널 채팅방 방장의 채팅방 끝내기 기능 부재

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#96]
1. 채널 채팅방의 주인(방장)일때 채팅방 나가기가 아니라 채팅방 끝내기가 있어야 합니다. 
2. 채팅방 끝내기 버튼을 누르면 해당하는 서버 api를 호출하고 채팅방이 폭파되어 모든 참여자가 나가게 되어야 합니다.
![캡처](https://user-images.githubusercontent.com/38745815/136668485-9398cf7f-d63d-46ac-ad93-7630ae405e38.PNG)

코드를 보니 기능이 부재한것으로 보이는데, 추가해주세요~~!

**Comment by sjsjsj1246** [comment]
이것도 개발 안됐습니다.
