### ISSUE TITLE
채널 채팅방 리뷰 미작성 채팅방 렌더링되지않음

### ISSUE THREAD

**Issue by Istiopaxx** [Jandy-SeoulTech/Jandy_Web_Front#97]
#### 채널 채팅방에서 리뷰를 작성하지 않았지만 나가있는 채팅방에 대해 리뷰 작성하기 버튼이 활성화 되지 않습니다.

![캡처2](https://user-images.githubusercontent.com/38745815/136668650-4696ecb5-569a-4a20-987c-0f82488e03bc.PNG)

위의 채팅방은 현재 로그인 사용자가 참여자로 참여한 채팅방이고, redux 상태를 보면 inactive 상태로 나가져있는 상태라는 것을 알수 있습니다. 또한 그 채팅방은 Close 상태입니다. 그렇다면 피그마에서처럼 나가져있고/리뷰가 안되어있으면 리뷰 작성 모달이 떠야하며, 나가져있고/리뷰가 되어있으면 목록에 없어야 합니다.

**Comment by sjsjsj1246** [comment]
사실 제출전 일정맞추기 어려워 개발을 덜끝냈던것같은데 마저 하겠습니다
